spring.profiles.active=${APP_PROFILE:test}

spring.output.ansi.enabled=NEVER

spring.jpa.open-in-view=false
# Ativa logs detalhados do Spring Security
 logging.level.org.springframework.core.env=DEBUG
logging.level.org.springframework.security.authentication=DEBUG
logging.level.org.springframework.security.core.userdetails=DEBUG
# Ativa logs detalhados do Spring Authorization Server
logging.level.org.springframework.security.oauth2=TRACE
logging.level.org.springframework.security=TRACE
logging.level.com.nimbusds.jose=TRACE

# spring.main.allow-circular-references=true

cors.origins=${CORS_ORIGINS:https://devsuperior.com.br,http://localhost:3000,http://localhost:5173}

security.oauth2.client.client-id=${CLIENT_ID:myclientid}
security.oauth2.client.client-secret=${CLIENT_SECRET:myclientsecret}

jwt.secret=${JWT_SECRET:uma-chave-secreta-muito-longa-e-segura-1234567890}
jwt.duration=${JWT_DURATION:86400}
spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER


